In [22]:
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

import scipy as sp 
import sklearn
import random 
import time 

from sklearn import preprocessing, model_selection

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import shuffle

In [23]:
data = pd.read_csv('weatherHistory.csv')

In [24]:
data = shuffle(data)

i = 5
data_to_predict = data[:i].reset_index(drop = True)
predict_conditions = data_to_predict.prediction 
predict_conditions = np.array(predict_conditions)
prediction = np.array(data_to_predict.drop(['prediction'],axis= 1))

print(prediction)

data = data[i:].reset_index(drop = True)

[[ 2.20000000e+00  8.90000000e-01  1.02361000e+03]
 [ 1.08888889e+00  9.20000000e-01  1.02990000e+03]
 [-1.12777778e+00  9.30000000e-01  1.03234000e+03]
 [ 6.11111111e+00  6.50000000e-01  1.02230000e+03]
 [ 2.68333333e+00  8.30000000e-01  1.02330000e+03]]


In [29]:
X = data.drop(['prediction'], axis = 1)
X = np.array(X)
Y = data['prediction'].astype(str)

In [30]:
encoder = LabelEncoder()
encoder.fit(Y)
Y = encoder.transform(Y)
Y = to_categorical(Y)
print(Y)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [31]:
train_x, test_x, train_y, test_y = model_selection.train_test_split(X,Y,test_size = 0.1, random_state = 0)

In [33]:
input_dim = len(data.columns) - 1

model = Sequential()
model.add(Dense(8, input_dim = input_dim , activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(3, activation = 'softmax'))

model.compile(loss = 'categorical_crossentropy' , optimizer = 'adam' , metrics = ['accuracy'] )

model.fit(train_x, train_y, epochs = 20, batch_size = 2)

Train on 86803 samples
Epoch 1/20
86803/86803 [==============================] - 49s 570us/sample - loss: 0.1015 - acc: 0.9698
Epoch 2/20
86803/86803 [==============================] - 45s 516us/sample - loss: 0.0625 - acc: 0.9822
Epoch 3/20
86803/86803 [==============================] - 44s 503us/sample - loss: 0.0605 - acc: 0.9838
Epoch 4/20
86803/86803 [==============================] - 44s 504us/sample - loss: 0.0581 - acc: 0.9847
Epoch 5/20
86803/86803 [==============================] - 44s 504us/sample - loss: 0.0579 - acc: 0.9843
Epoch 6/20
86803/86803 [==============================] - 44s 506us/sample - loss: 0.0633 - acc: 0.9841
Epoch 7/20
86803/86803 [==============================] - 41s 478us/sample - loss: 0.0876 - acc: 0.9830
Epoch 8/20
86803/86803 [==============================] - 45s 519us/sample - loss: 0.0607 - acc: 0.9856
Epoch 9/20
86803/86803 [==============================] - 48s 557us/sample - loss: 0.0616 - acc: 0.9860
Epoch 10/20
86803/86803 [================

In [34]:
scores = model.evaluate(test_x, test_y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

9645/9645 [==============================] - 1s 60us/sample - loss: 0.0344 - acc: 0.9927

acc: 99.27%


In [39]:
predictions = model.predict_classes(prediction)
print(predictions)

[1 1 2 1 1]


In [37]:
input = np.array([[9.472222222,0.89,1015.13]])
predict = model.predict_classes(input)
print(predict)

[1]


In [38]:
input = np.array([[-7.172222222,0.96,1005.25]])
predict = model.predict_classes(input)
print(predict)

[2]


In [40]:
from tensorflow.keras.models import load_model

model.save("./my_model/",save_format="tf")

INFO:tensorflow:Assets written to: ./my_model/assets


In [41]:
model2 = tf.keras.models.load_model('./my_model')

In [43]:
input = np.array([[-7.172222222,0.96,1005.25]])
predict = model2.predict_classes(input)
print(predict)

[2]
